# This is a basic workflow to help you get started with Actions

name: pr-build

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Lint LaTeX document
        uses: ChiefGokhlayeh/textidote-action@v5
        id: lint
        with:
          root_file: resume.tex
          args: --check en --dict en_US.dict
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: resume.tex
      - name: Upload Linit
        id: upload-lint
        uses: actions/upload-artifact@v3
        with:
          name: textidote_report
          path: report.html
      - name: Upload PDF
        id: upload-pdf
        uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: ./resume.pdf
          if-no-files-found: error
